server:
  port: 8082
spring:
  application:
    name: "ms_creditya_authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: db_creditya
    username: postgres
    password: postgres
    schema: public
logging:
  level:
    org.springframework.data.r2dbc: "DEBUG"
    org.springframework.r2dbc: "DEBUG"
    org.springframework.security: "DEBUG"
    org.springframework.web: "DEBUG"
    reactor.netty.http.server.HttpServerOperations: "DEBUG"
bezkoder:
  app:
    jwtSecret: "TuClaveSuperSecreta1234567890abcdef"
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 604800000
jwt:
  json-exp-roles: "/roles"
